import type { Campaign } from "@/types/campaign";

// 公式発表を2026-09-19に確認。対象店舗の公開状況も開催回ごとに管理。
export const campaignAdditions202609: Campaign[] = [
  {
    "paytype": "paypay",
    "prefectureSlug": "iwate",
    "citySlug": "noda",
    "prefecture": "岩手県",
    "city": "野田村",
    "offer": 20,
    "startDate": "2026-11-01",
    "endDate": "2026-11-30",
    "onepoint": "2000",
    "fullpoint": "5000",
    "campaigntitle": "野田村 PayPay 最大20％還元キャンペーン",
    "notice": "対象店舗は村と各決済事業者が指定する店舗です。2026年9月19日時点で今回の対象店舗一覧は準備中。還元上限は決済サービスごと。予算により早期終了する場合があります。",
    "datePublished": "2026-09-19",
    "dateModified": "2026-09-19",
    "officialUrl": "https://www.shokokai.com/noda/news/1537.html",
    "shopListStatus": "pending"
  },
  {
    "paytype": "aupay",
    "prefectureSlug": "iwate",
    "citySlug": "noda",
    "prefecture": "岩手県",
    "city": "野田村",
    "offer": 20,
    "startDate": "2026-11-01",
    "endDate": "2026-11-30",
    "onepoint": "2000",
    "fullpoint": "5000",
    "campaigntitle": "野田村 au PAY 最大20％還元キャンペーン",
    "notice": "対象店舗は村と各決済事業者が指定する店舗です。2026年9月19日時点で今回の対象店舗一覧は準備中。還元上限は決済サービスごと。予算により早期終了する場合があります。",
    "datePublished": "2026-09-19",
    "dateModified": "2026-09-19",
    "officialUrl": "https://www.shokokai.com/noda/news/1537.html",
    "shopListStatus": "pending"
  },
  {
    "paytype": "dbarai",
    "prefectureSlug": "iwate",
    "citySlug": "noda",
    "prefecture": "岩手県",
    "city": "野田村",
    "offer": 20,
    "startDate": "2026-11-01",
    "endDate": "2026-11-30",
    "onepoint": "2000",
    "fullpoint": "5000",
    "campaigntitle": "野田村 d払い 最大20％還元キャンペーン",
    "notice": "対象店舗は村と各決済事業者が指定する店舗です。2026年9月19日時点で今回の対象店舗一覧は準備中。還元上限は決済サービスごと。予算により早期終了する場合があります。",
    "datePublished": "2026-09-19",
    "dateModified": "2026-09-19",
    "officialUrl": "https://www.shokokai.com/noda/news/1537.html",
    "shopListStatus": "pending"
  },
  {
    "paytype": "paypay",
    "prefectureSlug": "gunma",
    "citySlug": "oizumi",
    "prefecture": "群馬県",
    "city": "大泉町",
    "offer": 20,
    "startDate": "2026-11-01",
    "endDate": "2026-11-30",
    "onepoint": "2000",
    "fullpoint": "4000",
    "campaigntitle": "大泉町 PayPay 最大20％還元キャンペーン",
    "notice": "第4弾。町内の中規模・小規模の指定加盟店が対象。対象店舗の詳細は後日公開予定です。早期終了する場合があります。",
    "datePublished": "2026-09-19",
    "dateModified": "2026-09-19",
    "officialUrl": "https://paypay.ne.jp/notice/20260915/cp-jichitai/",
    "shopListStatus": "pending"
  },
  {
    "paytype": "paypay",
    "prefectureSlug": "osaka",
    "citySlug": "hirakata",
    "prefecture": "大阪府",
    "city": "枚方市",
    "offer": 15,
    "startDate": "2026-11-01",
    "endDate": "2026-11-30",
    "onepoint": "500",
    "fullpoint": "3000",
    "campaigntitle": "枚方市 PayPay 最大15％還元キャンペーン",
    "notice": "市内の中小規模の指定加盟店が対象。決済方法ごとに開催月が異なります。対象店舗・利用方法の詳細は決定次第、市が公表します。",
    "datePublished": "2026-09-19",
    "dateModified": "2026-09-19",
    "officialUrl": "https://www.city.hirakata.osaka.jp/0000052840.html",
    "shopListStatus": "pending"
  },
  {
    "paytype": "dbarai",
    "prefectureSlug": "osaka",
    "citySlug": "hirakata",
    "prefecture": "大阪府",
    "city": "枚方市",
    "offer": 15,
    "startDate": "2026-12-01",
    "endDate": "2026-12-28",
    "onepoint": "500",
    "fullpoint": "3000",
    "campaigntitle": "枚方市 d払い 最大15％還元キャンペーン",
    "notice": "市内の中小規模の指定加盟店が対象。決済方法ごとに開催月が異なります。対象店舗・利用方法の詳細は決定次第、市が公表します。",
    "datePublished": "2026-09-19",
    "dateModified": "2026-09-19",
    "officialUrl": "https://www.city.hirakata.osaka.jp/0000052840.html",
    "shopListStatus": "pending"
  },
  {
    "paytype": "aupay",
    "prefectureSlug": "osaka",
    "citySlug": "hirakata",
    "prefecture": "大阪府",
    "city": "枚方市",
    "offer": 15,
    "startDate": "2027-01-04",
    "endDate": "2027-01-31",
    "onepoint": "500",
    "fullpoint": "3000",
    "campaigntitle": "枚方市 au PAY 最大15％還元キャンペーン",
    "notice": "市内の中小規模の指定加盟店が対象。決済方法ごとに開催月が異なります。対象店舗・利用方法の詳細は決定次第、市が公表します。",
    "datePublished": "2026-09-19",
    "dateModified": "2026-09-19",
    "officialUrl": "https://www.city.hirakata.osaka.jp/0000052840.html",
    "shopListStatus": "pending"
  }
];
