// ✅ 都道府県スラッグ・日本語名・エリアグループのマスター
export const prefectures = [
  { slug: "hokkaido", name: "北海道", group: "北海道・東北" },
  { slug: "aomori", name: "青森県", group: "北海道・東北" },
  { slug: "iwate", name: "岩手県", group: "北海道・東北" },
  { slug: "miyagi", name: "宮城県", group: "北海道・東北" },
  { slug: "akita", name: "秋田県", group: "北海道・東北" },
  { slug: "yamagata", name: "山形県", group: "北海道・東北" },
  { slug: "fukushima", name: "福島県", group: "北海道・東北" },
  { slug: "ibaraki", name: "茨城県", group: "関東" },
  { slug: "tochigi", name: "栃木県", group: "関東" },
  { slug: "gunma", name: "群馬県", group: "関東" },
  { slug: "saitama", name: "埼玉県", group: "関東" },
  { slug: "chiba", name: "千葉県", group: "関東" },
  { slug: "tokyo", name: "東京都", group: "関東" },
  { slug: "kanagawa", name: "神奈川県", group: "関東" },
  { slug: "niigata", name: "新潟県", group: "中部" },
  { slug: "toyama", name: "富山県", group: "中部" },
  { slug: "ishikawa", name: "石川県", group: "中部" },
  { slug: "fukui", name: "福井県", group: "中部" },
  { slug: "yamanashi", name: "山梨県", group: "中部" },
  { slug: "nagano", name: "長野県", group: "中部" },
  { slug: "gifu", name: "岐阜県", group: "中部" },
  { slug: "shizuoka", name: "静岡県", group: "中部" },
  { slug: "aichi", name: "愛知県", group: "中部" },
  { slug: "mie", name: "三重県", group: "近畿" },
  { slug: "shiga", name: "滋賀県", group: "近畿" },
  { slug: "kyoto", name: "京都府", group: "近畿" },
  { slug: "osaka", name: "大阪府", group: "近畿" },
  { slug: "hyogo", name: "兵庫県", group: "近畿" },
  { slug: "nara", name: "奈良県", group: "近畿" },
  { slug: "wakayama", name: "和歌山県", group: "近畿" },
  { slug: "tottori", name: "鳥取県", group: "中国" },
  { slug: "shimane", name: "島根県", group: "中国" },
  { slug: "okayama", name: "岡山県", group: "中国" },
  { slug: "hiroshima", name: "広島県", group: "中国" },
  { slug: "yamaguchi", name: "山口県", group: "中国" },
  { slug: "tokushima", name: "徳島県", group: "四国" },
  { slug: "kagawa", name: "香川県", group: "四国" },
  { slug: "ehime", name: "愛媛県", group: "四国" },
  { slug: "kochi", name: "高知県", group: "四国" },
  { slug: "fukuoka", name: "福岡県", group: "九州・沖縄" },
  { slug: "saga", name: "佐賀県", group: "九州・沖縄" },
  { slug: "nagasaki", name: "長崎県", group: "九州・沖縄" },
  { slug: "kumamoto", name: "熊本県", group: "九州・沖縄" },
  { slug: "oita", name: "大分県", group: "九州・沖縄" },
  { slug: "miyazaki", name: "宮崎県", group: "九州・沖縄" },
  { slug: "kagoshima", name: "鹿児島県", group: "九州・沖縄" },
  { slug: "okinawa", name: "沖縄県", group: "九州・沖縄" },
];

// ✅ グループ一覧（重複除去）
export const prefectureGroups = Array.from(new Set(prefectures.map(p => p.group)));